# -*- coding: utf-8 -*-
"""Copy of ai study assistant

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fDmzRsLzLJ0fPyl6n5ukiIQL14UKojJq
"""

!pip install flask requests pyngrok flask-cors -q
print("✅ All libraries installed!")

import requests
import threading
import time
from flask import Flask, request, jsonify, render_template_string
from flask_cors import CORS
from pyngrok import ngrok
import os

# ── Keys ──
OPENROUTER_API_KEY=your_key
MAKE_WEBHOOK_URL=your_webhook
NGROK_TOKEN=your_token
MODEL = "google/gemma-4-26b-a4b-it:free"

# ── AI Functions ──
def call_openrouter(system_prompt, user_message):
    try:
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost",
                "X-Title": "Study Assistant"
            },
            json={
                "model": MODEL,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message}
                ]
            },
            timeout=60
        )
        print("API Status:", response.status_code)
        return response.json()["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"API ERROR: {e}")
        return "Sorry, AI is busy. Please try again."

def summarize_notes(notes):
    system = "You are an expert study assistant. Summarize the provided study notes into clear bullet points. Highlight key concepts and important facts."
    return call_openrouter(system, f"Summarize these notes:\n\n{notes}")

def generate_questions(notes, count=7):
    system = f"You are an exam question creator. Generate exactly {count} revision questions based on the notes. Number each question. Then add ANSWERS section."
    return call_openrouter(system, f"Notes:\n\n{notes}")

def chat_with_notes(notes, question, history=[]):
    system = f"You are an AI study assistant. Answer questions ONLY based on the study notes below.\n\n=== STUDY NOTES ===\n{notes}\n=== END ==="
    messages = [{"role": "system", "content": system}]
    for turn in history[-6:]:
        messages.append(turn)
    messages.append({"role": "user", "content": question})
    try:
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost",
                "X-Title": "Study Assistant"
            },
            json={"model": MODEL, "messages": messages},
            timeout=60
        )
        return response.json()["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"Chat error: {e}")
        return "Sorry, AI is busy. Please try again in a moment."

def trigger_make(notes, summary):
    if not MAKE_WEBHOOK_URL:
        return
    try:
        result = requests.post(
            MAKE_WEBHOOK_URL,
            json={
                "notes": notes[:500],
                "summary": summary,
                "event": "summarize"
            },
            timeout=10
        )
        print(f"✅ Make.com triggered! Status: {result.status_code}")
    except Exception as e:
        print(f"Make.com error: {e}")

# ── Flask App ──
app = Flask(__name__)
CORS(app)

HTML = """
<!DOCTYPE html>
<html>
<head>
  <title>AI Study Assistant</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #0f1117; color: #e8eaf0; min-height: 100vh; }
    header { background: #1a1d27; border-bottom: 1px solid #2e3248; padding: 16px 24px; display: flex; align-items: center; gap: 10px; }
    header h1 { font-size: 18px; }
    header p  { font-size: 12px; color: #8890a8; }
    .wrap { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; padding: 20px 24px; }
    @media(max-width:700px){ .wrap { grid-template-columns: 1fr; } }
    .card { background: #1a1d27; border: 1px solid #2e3248; border-radius: 12px; padding: 18px; display: flex; flex-direction: column; gap: 12px; }
    h2 { font-size: 14px; font-weight: 600; }
    textarea, input[type=text] { background: #222638; border: 1px solid #2e3248; border-radius: 8px; color: #e8eaf0; font-size: 14px; padding: 12px; width: 100%; outline: none; }
    textarea:focus, input:focus { border-color: #6c63ff; }
    textarea { min-height: 200px; resize: vertical; line-height: 1.6; }
    .btn { padding: 10px 18px; border-radius: 8px; border: none; font-size: 14px; font-weight: 500; cursor: pointer; transition: .2s; width: 100%; }
    .primary { background: #6c63ff; color: #fff; }
    .primary:hover { background: #5753e8; }
    .primary:disabled { opacity: .5; cursor: not-allowed; }
    .output { background: #222638; border: 1px solid #2e3248; border-radius: 8px; padding: 12px; font-size: 14px; line-height: 1.7; min-height: 60px; white-space: pre-wrap; }
    .muted { color: #8890a8; font-style: italic; }
    .tabs { display: flex; gap: 0; border-bottom: 1px solid #2e3248; margin-bottom: 12px; }
    .tab { padding: 8px 16px; font-size: 13px; border: none; background: transparent; color: #8890a8; cursor: pointer; border-bottom: 2px solid transparent; }
    .tab.on { color: #6c63ff; border-bottom-color: #6c63ff; }
    .t { display: none; flex-direction: column; gap: 12px; }
    .t.on { display: flex; }
    .chat-box { display: flex; flex-direction: column; gap: 8px; max-height: 280px; overflow-y: auto; }
    .msg { padding: 9px 13px; border-radius: 8px; font-size: 14px; max-width: 85%; line-height: 1.5; }
    .msg.u { background: #6c63ff; color: #fff; align-self: flex-end; }
    .msg.a { background: #222638; border: 1px solid #2e3248; align-self: flex-start; }
    .row { display: flex; gap: 8px; }
    .row input { flex: 1; }
    .row .btn { width: auto; padding: 10px 16px; }
    select { background: #222638; border: 1px solid #2e3248; color: #e8eaf0; padding: 7px 10px; border-radius: 6px; font-size: 14px; }
    .hint { font-size: 12px; color: #8890a8; line-height: 1.5; background: rgba(108,99,255,.06); border: 1px solid rgba(108,99,255,.15); border-radius: 8px; padding: 10px; }
    .tag { font-size: 11px; background: rgba(108,99,255,.15); color: #6c63ff; padding: 3px 10px; border-radius: 20px; display: inline-block; margin-top: 4px; }
  </style>
</head>
<body>
<header>
  <span>📚</span>
  <div><h1>AI Study Assistant</h1><p>Summarize · Questions · Chat</p></div>
</header>
<div class="wrap">
  <div class="card">
    <h2>📝 Your Notes</h2>
    <textarea id="notes" placeholder="Paste your study notes here..."></textarea>
    <div class="hint">1. Paste notes above<br>2. Use the tools on the right<br>3. Summary auto-saves to Google Sheets + Gmail + Drive</div>
    <button class="btn" style="background:#222638;border:1px solid #2e3248;" onclick="loadSample()">Load sample notes</button>
  </div>
  <div class="card">
    <h2>🤖 AI Tools</h2>
    <div class="tabs">
      <button class="tab on" onclick="tab('sum',this)">Summarize</button>
      <button class="tab"    onclick="tab('q',  this)">Questions</button>
      <button class="tab"    onclick="tab('cht', this)">Chat</button>
    </div>
    <div class="t on" id="t-sum">
      <button class="btn primary" id="b-sum" onclick="doSummarize()">✨ Summarize my notes</button>
      <div class="output muted" id="out-sum">Summary will appear here…</div>
      <span class="tag" id="make-tag" style="display:none">✅ Saved to Google Sheets + Gmail sent + Google Drive updated</span>
    </div>
    <div class="t" id="t-q">
      <div style="display:flex;align-items:center;gap:10px;">
        <label style="font-size:13px;color:#8890a8;">Questions:</label>
        <select id="qcount"><option>5</option><option selected>7</option><option>10</option></select>
      </div>
      <button class="btn primary" id="b-q" onclick="doQuestions()">🎯 Generate questions</button>
      <div class="output muted" id="out-q">Questions will appear here…</div>
    </div>
    <div class="t" id="t-cht">
      <div class="chat-box" id="chat-box">
        <div class="msg a">Hi! Paste your notes on the left, then ask me anything 📖</div>
      </div>
      <div class="row">
        <input type="text" id="chat-in" placeholder="Ask about your notes…" onkeydown="if(event.key==='Enter')doChat()"/>
        <button class="btn primary" id="b-chat" onclick="doChat()">Send</button>
      </div>
    </div>
  </div>
</div>
<script>
  let history = [];
  function tab(name, el) {
    document.querySelectorAll('.tab').forEach(b=>b.classList.remove('on'));
    document.querySelectorAll('.t').forEach(t=>t.classList.remove('on'));
    el.classList.add('on');
    document.getElementById('t-'+name).classList.add('on');
  }
  function notes() { return document.getElementById('notes').value.trim(); }
  function setLoading(btnId, on) {
    const b = document.getElementById(btnId);
    b.disabled = on;
    if (on) b.dataset.orig = b.textContent;
    b.textContent = on ? 'Loading…' : b.dataset.orig;
  }
  async function doSummarize() {
    if (!notes()) { alert('Paste your notes first!'); return; }
    setLoading('b-sum', true);
    const r = await fetch('/api/summarize', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify({notes: notes()})
    }).then(r=>r.json());
    document.getElementById('out-sum').textContent = r.summary || r.error;
    document.getElementById('out-sum').classList.remove('muted');
    document.getElementById('make-tag').style.display = 'inline-block';
    setLoading('b-sum', false);
  }
  async function doQuestions() {
    if (!notes()) { alert('Paste your notes first!'); return; }
    setLoading('b-q', true);
    const count = document.getElementById('qcount').value;
    const r = await fetch('/api/questions', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify({notes: notes(), count: parseInt(count)})
    }).then(r=>r.json());
    document.getElementById('out-q').textContent = r.questions || r.error;
    document.getElementById('out-q').classList.remove('muted');
    setLoading('b-q', false);
  }
  async function doChat() {
    if (!notes()) { alert('Paste your notes first!'); return; }
    const msg = document.getElementById('chat-in').value.trim();
    if (!msg) return;
    addMsg(msg, 'u');
    history.push({role:'user', content:msg});
    document.getElementById('chat-in').value = '';
    setLoading('b-chat', true);
    const r = await fetch('/api/chat', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify({notes: notes(), message: msg, history: history})
    }).then(r=>r.json());
    addMsg(r.reply || r.error, 'a');
    history.push({role:'assistant', content: r.reply || r.error});
    setLoading('b-chat', false);
  }
  function addMsg(text, who) {
    const box = document.getElementById('chat-box');
    const d = document.createElement('div');
    d.className = 'msg ' + who;
    d.textContent = text;
    box.appendChild(d);
    box.scrollTop = box.scrollHeight;
  }
  function loadSample() {
    document.getElementById('notes').value = `Photosynthesis is how plants convert sunlight into glucose.\n\nEquation: 6CO2 + 6H2O + light → C6H12O6 + 6O2\n\nTwo stages:\n1. Light-dependent reactions (thylakoid): water split, O2 released, ATP + NADPH made\n2. Calvin Cycle (stroma): CO2 fixed using ATP + NADPH → glucose\n\nFactors:\n- Light intensity\n- CO2 concentration\n- Temperature (best at 25-35°C)\n\nChlorophyll absorbs red and blue light. Green is reflected.`;
  }
</script>
</body>
</html>
"""

@app.route("/")
def home():
    return render_template_string(HTML)

@app.route("/api/summarize", methods=["POST"])
def api_summarize():
    data = request.get_json()
    notes = data.get("notes", "").strip()
    if not notes:
        return jsonify({"error": "No notes provided"}), 400
    summary = summarize_notes(notes)
    trigger_make(notes, summary)
    return jsonify({"summary": summary})

@app.route("/api/questions", methods=["POST"])
def api_questions():
    data = request.get_json()
    notes = data.get("notes", "").strip()
    count = data.get("count", 7)
    if not notes:
        return jsonify({"error": "No notes provided"}), 400
    result = generate_questions(notes, count)
    return jsonify({"questions": result})

@app.route("/api/chat", methods=["POST"])
def api_chat():
    data = request.get_json()
    notes = data.get("notes", "").strip()
    message = data.get("message", "").strip()
    history = data.get("history", [])
    if not message:
        return jsonify({"error": "No message provided"}), 400
    reply = chat_with_notes(notes, message, history)
    return jsonify({"reply": reply})

# ── Launch ──
import os
os.system("fuser -k 5004/tcp")
time.sleep(1)

print("✅ Flask app defined!")
ngrok.kill()
time.sleep(2)
ngrok.set_auth_token(NGROK_TOKEN)

def run_flask():
    app.run(port=5004, use_reloader=False)

t = threading.Thread(target=run_flask)
t.daemon = True
t.start()
time.sleep(3)

public_url = ngrok.connect(5004)
print("=" * 50)
print(f"🌐 YOUR APP URL: {public_url}")
print("=" * 50)

import requests
import threading
import time
from flask import Flask, request, jsonify, render_template_string
from flask_cors import CORS
from pyngrok import ngrok

# ── Keys ──
OPENROUTER_API_KEY = "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"
MAKE_WEBHOOK_URL = "https://hook.eu1.make.com/m28w8dl3iyapk0pvvfhui5r5fva6n36x"

# ── AI Functions ──
def call_openrouter(system_prompt, user_message):
    try:
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost",
                "X-Title": "Study Assistant"
            },
            json={
                "model": "google/gemma-4-26b-a4b-it:free",
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_message}
                ]
            },
            timeout=60
        )
        print("API Status:", response.status_code)
        return response.json()["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"API ERROR: {e}")
        return f"Sorry, AI is busy. Please try again."

def summarize_notes(notes):
    system = "You are an expert study assistant. Summarize the provided study notes into clear bullet points. Highlight key concepts and important facts."
    return call_openrouter(system, f"Summarize these notes:\n\n{notes}")

def generate_questions(notes, count=7):
    system = f"You are an exam question creator. Generate exactly {count} revision questions based on the notes. Number each question. Then add ANSWERS section."
    return call_openrouter(system, f"Notes:\n\n{notes}")

def chat_with_notes(notes, question, history=[]):
    system = f"You are an AI study assistant. Answer questions ONLY based on the study notes below.\n\n=== STUDY NOTES ===\n{notes}\n=== END ==="
    messages = [{"role": "system", "content": system}]
    for turn in history[-6:]:
        messages.append(turn)
    messages.append({"role": "user", "content": question})
    try:
        response = requests.post(
            url="https://openrouter.ai/api/v1/chat/completions",
            headers={
                "Authorization": f"Bearer {OPENROUTER_API_KEY}",
                "Content-Type": "application/json",
                "HTTP-Referer": "http://localhost",
                "X-Title": "Study Assistant"
            },
            json={
                "model": "google/gemma-4-26b-a4b-it:free",
                "messages": messages
            },
            timeout=60
        )
        return response.json()["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"Chat error: {e}")
        return "Sorry, AI is busy. Please try again in a moment."

def trigger_make(notes, summary):
    if not MAKE_WEBHOOK_URL:
        return
    try:
        requests.post(
            MAKE_WEBHOOK_URL,
            json={
                "notes": notes[:500],
                "summary": summary,
                "event": "summarize"
            },
            timeout=10
        )
        print("✅ Make.com triggered!")
    except Exception as e:
        print(f"Make.com error: {e}")

# ── Flask App ──
app = Flask(__name__)
CORS(app)

HTML = """
<!DOCTYPE html>
<html>
<head>
  <title>AI Study Assistant</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, sans-serif; background: #0f1117; color: #e8eaf0; min-height: 100vh; }
    header { background: #1a1d27; border-bottom: 1px solid #2e3248; padding: 16px 24px; display: flex; align-items: center; gap: 10px; }
    header h1 { font-size: 18px; }
    header p  { font-size: 12px; color: #8890a8; }
    .wrap { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; padding: 20px 24px; }
    @media(max-width:700px){ .wrap { grid-template-columns: 1fr; } }
    .card { background: #1a1d27; border: 1px solid #2e3248; border-radius: 12px; padding: 18px; display: flex; flex-direction: column; gap: 12px; }
    h2 { font-size: 14px; font-weight: 600; }
    textarea, input[type=text] { background: #222638; border: 1px solid #2e3248; border-radius: 8px; color: #e8eaf0; font-size: 14px; padding: 12px; width: 100%; outline: none; }
    textarea:focus, input:focus { border-color: #6c63ff; }
    textarea { min-height: 200px; resize: vertical; line-height: 1.6; }
    .btn { padding: 10px 18px; border-radius: 8px; border: none; font-size: 14px; font-weight: 500; cursor: pointer; transition: .2s; width: 100%; }
    .primary { background: #6c63ff; color: #fff; }
    .primary:hover { background: #5753e8; }
    .primary:disabled { opacity: .5; cursor: not-allowed; }
    .output { background: #222638; border: 1px solid #2e3248; border-radius: 8px; padding: 12px; font-size: 14px; line-height: 1.7; min-height: 60px; white-space: pre-wrap; }
    .muted { color: #8890a8; font-style: italic; }
    .tabs { display: flex; gap: 0; border-bottom: 1px solid #2e3248; margin-bottom: 12px; }
    .tab { padding: 8px 16px; font-size: 13px; border: none; background: transparent; color: #8890a8; cursor: pointer; border-bottom: 2px solid transparent; }
    .tab.on { color: #6c63ff; border-bottom-color: #6c63ff; }
    .t { display: none; flex-direction: column; gap: 12px; }
    .t.on { display: flex; }
    .chat-box { display: flex; flex-direction: column; gap: 8px; max-height: 280px; overflow-y: auto; }
    .msg { padding: 9px 13px; border-radius: 8px; font-size: 14px; max-width: 85%; line-height: 1.5; }
    .msg.u { background: #6c63ff; color: #fff; align-self: flex-end; }
    .msg.a { background: #222638; border: 1px solid #2e3248; align-self: flex-start; }
    .row { display: flex; gap: 8px; }
    .row input { flex: 1; }
    .row .btn { width: auto; padding: 10px 16px; }
    select { background: #222638; border: 1px solid #2e3248; color: #e8eaf0; padding: 7px 10px; border-radius: 6px; font-size: 14px; }
    .hint { font-size: 12px; color: #8890a8; line-height: 1.5; background: rgba(108,99,255,.06); border: 1px solid rgba(108,99,255,.15); border-radius: 8px; padding: 10px; }
    .tag { font-size: 11px; background: rgba(108,99,255,.15); color: #6c63ff; padding: 3px 10px; border-radius: 20px; display: inline-block; margin-top: 4px; }
  </style>
</head>
<body>
<header>
  <span>📚</span>
  <div><h1>AI Study Assistant</h1><p>Summarize · Questions · Chat</p></div>
</header>
<div class="wrap">
  <div class="card">
    <h2>📝 Your Notes</h2>
    <textarea id="notes" placeholder="Paste your study notes here..."></textarea>
    <div class="hint">1. Paste notes above<br>2. Use the tools on the right<br>3. Summary auto-saves to Google Sheets + Gmail</div>
    <button class="btn" style="background:#222638;border:1px solid #2e3248;" onclick="loadSample()">Load sample notes</button>
  </div>
  <div class="card">
    <h2>🤖 AI Tools</h2>
    <div class="tabs">
      <button class="tab on" onclick="tab('sum',this)">Summarize</button>
      <button class="tab"    onclick="tab('q',  this)">Questions</button>
      <button class="tab"    onclick="tab('cht', this)">Chat</button>
    </div>
    <div class="t on" id="t-sum">
      <button class="btn primary" id="b-sum" onclick="doSummarize()">✨ Summarize my notes</button>
      <div class="output muted" id="out-sum">Summary will appear here…</div>
      <span class="tag" id="make-tag" style="display:none">✅ Saved to Google Sheets + Gmail sent + Google drive updated</span>
    </div>
    <div class="t" id="t-q">
      <div style="display:flex;align-items:center;gap:10px;">
        <label style="font-size:13px;color:#8890a8;">Questions:</label>
        <select id="qcount"><option>5</option><option selected>7</option><option>10</option></select>
      </div>
      <button class="btn primary" id="b-q" onclick="doQuestions()">🎯 Generate questions</button>
      <div class="output muted" id="out-q">Questions will appear here…</div>
    </div>
    <div class="t" id="t-cht">
      <div class="chat-box" id="chat-box">
        <div class="msg a">Hi! Paste your notes on the left, then ask me anything 📖</div>
      </div>
      <div class="row">
        <input type="text" id="chat-in" placeholder="Ask about your notes…" onkeydown="if(event.key==='Enter')doChat()"/>
        <button class="btn primary" id="b-chat" onclick="doChat()">Send</button>
      </div>
    </div>
  </div>
</div>
<script>
  let history = [];
  function tab(name, el) {
    document.querySelectorAll('.tab').forEach(b=>b.classList.remove('on'));
    document.querySelectorAll('.t').forEach(t=>t.classList.remove('on'));
    el.classList.add('on');
    document.getElementById('t-'+name).classList.add('on');
  }
  function notes() { return document.getElementById('notes').value.trim(); }
  function setLoading(btnId, on) {
    const b = document.getElementById(btnId);
    b.disabled = on;
    if (on) b.dataset.orig = b.textContent;
    b.textContent = on ? 'Loading…' : b.dataset.orig;
  }
  async function doSummarize() {
    if (!notes()) { alert('Paste your notes first!'); return; }
    setLoading('b-sum', true);
    const r = await fetch('/api/summarize', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify({notes: notes()})
    }).then(r=>r.json());
    document.getElementById('out-sum').textContent = r.summary || r.error;
    document.getElementById('out-sum').classList.remove('muted');
    document.getElementById('make-tag').style.display = 'inline-block';
    setLoading('b-sum', false);
  }
  async function doQuestions() {
    if (!notes()) { alert('Paste your notes first!'); return; }
    setLoading('b-q', true);
    const count = document.getElementById('qcount').value;
    const r = await fetch('/api/questions', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify({notes: notes(), count: parseInt(count)})
    }).then(r=>r.json());
    document.getElementById('out-q').textContent = r.questions || r.error;
    document.getElementById('out-q').classList.remove('muted');
    setLoading('b-q', false);
  }
  async function doChat() {
    if (!notes()) { alert('Paste your notes first!'); return; }
    const msg = document.getElementById('chat-in').value.trim();
    if (!msg) return;
    addMsg(msg, 'u');
    history.push({role:'user', content:msg});
    document.getElementById('chat-in').value = '';
    setLoading('b-chat', true);
    const r = await fetch('/api/chat', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify({notes: notes(), message: msg, history: history})
    }).then(r=>r.json());
    addMsg(r.reply || r.error, 'a');
    history.push({role:'assistant', content: r.reply || r.error});
    setLoading('b-chat', false);
  }
  function addMsg(text, who) {
    const box = document.getElementById('chat-box');
    const d = document.createElement('div');
    d.className = 'msg ' + who;
    d.textContent = text;
    box.appendChild(d);
    box.scrollTop = box.scrollHeight;
  }
  function loadSample() {
    document.getElementById('notes').value = `Photosynthesis is how plants convert sunlight into glucose.\n\nEquation: 6CO2 + 6H2O + light → C6H12O6 + 6O2\n\nTwo stages:\n1. Light-dependent reactions (thylakoid): water split, O2 released, ATP + NADPH made\n2. Calvin Cycle (stroma): CO2 fixed using ATP + NADPH → glucose\n\nFactors:\n- Light intensity\n- CO2 concentration\n- Temperature (best at 25-35°C)\n\nChlorophyll absorbs red and blue light. Green is reflected.`;
  }
</script>
</body>
</html>
"""

@app.route("/")
def home():
    return render_template_string(HTML)

@app.route("/api/summarize", methods=["POST"])
def api_summarize():
    data = request.get_json()
    notes = data.get("notes", "").strip()
    if not notes:
        return jsonify({"error": "No notes provided"}), 400
    summary = summarize_notes(notes)
    trigger_make(notes, summary)
    return jsonify({"summary": summary})

@app.route("/api/questions", methods=["POST"])
def api_questions():
    data = request.get_json()
    notes = data.get("notes", "").strip()
    count = data.get("count", 7)
    if not notes:
        return jsonify({"error": "No notes provided"}), 400
    result = generate_questions(notes, count)
    return jsonify({"questions": result})

@app.route("/api/chat", methods=["POST"])
def api_chat():
    data = request.get_json()
    notes = data.get("notes", "").strip()
    message = data.get("message", "").strip()
    history = data.get("history", [])
    if not message:
        return jsonify({"error": "No message provided"}), 400
    reply = chat_with_notes(notes, message, history)
    return jsonify({"reply": reply})

# ── Launch ──
print("✅ Flask app defined!")
ngrok.kill()
ngrok.set_auth_token("3FfkzQBTgpPSuhA1uvpf6UguTmv_4ejNgZ2y9Xc7TR4kvYB6T")

def run_flask():
    app.run(port=5001, use_reloader=False)

t = threading.Thread(target=run_flask)
t.daemon = True
t.start()
time.sleep(3)

public_url = ngrok.connect(5001)
print("=" * 50)
print(f"🌐 YOUR APP URL: {public_url}")
print("=" * 50)